version: "3"

services:
    proxy:
        depends_on:
            - web
        image: nginx:alpine
        container_name: proxy
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./bora-crawler/proxy/nginx.conf:/etc/nginx/nginx.conf

    web:
        image: nginx:latest
        container_name: web
        restart: always
        ports:
            - "8080:8080"
        volumes: 
            - ./bora-crawler/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./bora-crawler/flask_docker/flask_app/templates:/usr/share/nginx/html
            - ./bora-crawler/flask_docker/flask_app/static:/usr/share/nginx/static
            - ./bora-crawler/flask_docker/flask_app/utils/chromedriver:/usr/share/nginx/utils/chromedriver
    
    flask:
        build:
            context: ./bora-crawler/flask_docker
            dockerfile: Dockerfile
        container_name: flask
        restart: always
        ports: 
            - "24810:24810"
        volumes:
            - ./bora-crawler/flask_docker/flask_app/static:/usr/src/flask_app/static
        command: gunicorn -w 1 -b 0.0.0.0:24810 --timeout=300 wsgi:app

    torchserve:
        build:
            context: ./bora-crawler/torchserve
            dockerfile: Dockerfile
        container_name: torchserve
        restart: always
        ports:
            - "30371:30371"

    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./bora-web/frontend
        volumes:
            - /app/node_modules
            - ./bora-web/frontend:/app
        stdin_open: true

    nginx: 
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./bora-web/nginx
        ports: 
            - "3000:80"

    backend:
        build: 
            dockerfile: Dockerfile.dev
            context: ./bora-web/backend
        container_name: app_backend
        volumes:
            - /app/node_modules
            - ./bora-web/backend:/app
        ports: 
            - "5000:5000"